version: "3.7"
services:
  grafana:
    image: grafana/grafana:5.4.2 # Matches Scylla Monitor 2.4
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.rule: PathPrefix(`/grafana`)
      traefik.http.routers.grafana.middlewares: grafana-stripprefix
      traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes: /grafana
      traefik.http.routers.grafana.entrypoints: web
  traefik:
    image: traefik:v2.1.6
    container_name: traefik
    command:
      # - "--log.level": DEBUG
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
